# Custom Language File for Launcher Customizer

[ejs.app]
title = "SC Launcher"

[ejs.landing]
mediaHomeURL = "#"
mediaLinkURL = "#"
mediaMapURL = "#"
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "안녕하세요."
welcomeDescription = "생존캠프:마인크래프트입니다."
welcomeDescCTA = "저희 디스코드에서 다양한 생존 게임을 체험해보세요!"
